# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-10"

[[extensions]]
name = "MontyPay Payment Gateway Extension"
handle = "montypay-payment-gateway-extension"
type = "payments_extension"


merchant_label = "Offsite Payments App Extension"
payment_session_url = "https://shopifyapp.montypay.com/app/payment_session"
refund_session_url = "https://shopifyapp.montypay.com/app/refund_session"
#capture_session_url = ""
#void_session_url = ""
supports_oversell_protection = false
# List of ISO 3166 (alpha-2) country codes your app is available for installation by merchants. Learn more:
# https://www.iso.org/iso-3166-country-codes.html
supported_countries = ["LB", "JO", "NG", "BH", "QA", "US", "AE", "ID", "FR", "DE", "GB", "SA", "KW"]
# List payment method names that your payment extension will support. Learn more:
# https://github.com/activemerchant/payment_icons/blob/master/db/payment_icons.yml
supported_payment_methods = ["visa", "master", "american_express", "jcb","kfast", "knet", "mada"]
supports_3ds = true
supports_installments = false
supports_deferred_payments = false
test_mode_available = true

# buyer_label = ""
# [[extensions.buyer_label_translations]]
# label = "translation"
# locale = "fr"

# [[extensions.buyer_label_translations]]
# label = "translation"
# locale = "da"

[[extensions.targeting]]
target = "payments.offsite.render"
